[workspace]
authors = ["travellerse"]
channels = ["conda-forge"]
name = "RainClassroomAssistant"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
pyqt5 = ">=5.15.11, <6"
pyttsx3 = ">=2.99, <3"
requests = ">=2.32.5, <3"
urllib3 = ">=2.6.3, <3"
websocket-client = ">=1.9.0, <2"
fpdf = ">=1.7.2, <2"
numpy = ">=2.4.2, <3"
deepdiff = ">=8.6.1, <9"
pillow = ">=12.1.1, <13"
pypdf2 = ">=3.0.1, <4"
apprise = ">=1.9.7, <2"
pyinstaller = ">=6.19.0, <7"
pre-commit = ">=4.5.1, <5"
